// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxgpxbfdzmdkenlulwue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Z3B4YmZkem1ka2VubHVsd3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDMzODMsImV4cCI6MjA3MjgxOTM4M30.wGG1ZEe0PD52AqmdCZvRftNH0moVRSO-OEaaZzwpbQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});